### ISSUE TITLE
logging re-triggered on subsequent tests

### ISSUE THREAD

**Issue by willscott** [OpenObservatory/gooni#6]
After adding the Dash test in the performance group, I notice that logging seems to get re-added with each subsequent test.

When running `ooni run performance`, one sees expected output during Dash run, but then when NDT runs all log lines are duplicated, e.g.

```
   • Submitting test results; please be patient...
   • Submitting test results; please be patient...
   • Results successfully submitted
   • Results successfully submitted
   • OnProgress: 0.950000 - ending the test
   • OnProgress: 0.950000 - ending the test
   • Closing report; please be patient...
   • Closing report; please be patient...
   • Report successfully closed
   • Report successfully closed
   • OnProgress: 1.000000 - test complete
   • OnProgress: 1.000000 - test complete
```

**Comment by hellais** [comment]
Good call. The root cause of this was that the handler map was a global instead of being per nettest. To overcome this I refactored it to be instead part of the Nettest and created a `NewNettest` constructor. See: https://github.com/measurement-kit/go-measurement-kit/commit/e6bf66a9d942b6e416c992ae7d0e1fa406c26cd6.

If you pull from the current master and run:

```
dep ensure -update github.com/measurement-kit/go-measurement-kit
```

You should find it fixed.
